### ISSUE TITLE
GetCreditCardVendor does not work as expected

### ISSUE THREAD

**Issue by intrueder** [anna41/task_for_kottans#2]
Pass number `3530111333300000` to `GetCreditCardVendor` method
Expected result: `"JCB"`
Actual result: `"Unknown"`

Pass number `5105105105105100` to `GetCreditCardVendor` method
Expected result: `"MasterCard"`
Actual result: `"Unknown"`

Pass number `4911830000000` to `GetCreditCardVendor` method
Expected result: `"VISA"`
Actual result: `"Unknown"`

**Comment by anna41** [comment]
It already works

**Comment by intrueder** [comment]
Not yet :)

``` cs
string[] vendors = { "American Express", "Maestro", "MastCard", "Visa", "JCD", "Unknown" };
```

Fix names for "MasterCard" and "JCB" please

**Comment by intrueder** [comment]
Sorry, but should reopen this issue. I have problems with some card numbers..
`3530111333300000` ER: "JCB", but program results with "Unknown"
`3566 0020 2036 0505` ER: "JCB", but program results with "Unknown"
`5000000000000611` ER: "Maestro", AR: "Unknown"

**Comment by anna41** [comment]
Fixed
