### ISSUE TITLE
Next card number is generated when it shouldn't

### ISSUE THREAD

**Issue by intrueder** [anna41/task_for_kottans#4]
Pass the number `"4999999999999999993"` (VISA) into method `GenerateNextCreditCardNumber`
Expected result: exeption or some message like "no more card numbers available for this vendor"
Actual result: `"5000000000000000005"` (Maestro)

**Comment by anna41** [comment]
Fixed

**Comment by intrueder** [comment]
Still reproducable

**Comment by anna41** [comment]
Sorry,but when i run a program with this number,I have this result : "no more card numbers available for this vendor". Maybe, load last version and try again.
![1](https://cloud.githubusercontent.com/assets/19194015/15098626/dd8b9e70-1549-11e6-9252-416e5b5deee2.JPG)

**Comment by intrueder** [comment]
Ah, I did not check `Main` method, only `GenerateNextCreditCardNumber`. Ok, closing the issue.
